AllCops:
  Exclude:
    - "**/Rakefile"
    - "**/spec/**/*"
    - "**/db/schema.rb"
  NewCops: enable
  TargetRubyVersion: 3.1

Bundler/OrderedGems:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/LineEndStringConcatenationIndentation:
  Enabled: false
Layout/LineLength:
  Max: 120
Lint/EmptyClass:
  Enabled: false
Lint/EmptyFile:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/BlockForwarding:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Security/Open:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/SelfAssignment:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolProc:
  Enabled: false
Style/WordArray:
  Enabled: false
